### ISSUE TITLE
Todo list refactors debugging tooling

### ISSUE THREAD

**Issue by mr-zwets** [CashScript/cashscript#204]
after finishing #172 there are still refactors of the code that we want to do

- [x] Make bitauthUri required in FailedTransactionError once the advanced transaction builder supports debugging
- [x] In `generateTemplateScenarios`, make `currentBlockHeight` and `currentBlockTime` configurable
- [x] In `generateTemplateScenarioTransaction`, use `zip()` to merge libauth input and cashscript input, instead of using `[index]`
- [x] In LibauthTemplate.ts, see if we can merge `formatBytecodeForDebugging` with the code from @cashscript/utils -> script.ts
- [x] Investigate refactoring / moving `serialiseTokenDetails` in LibauthTemplate.ts
- [x] Investigate if we change the buildTemplate signature so we don't need to pass in both transaction and transactionHex?

other:
- [x] audit changes to syntax highlighting plugin
- [x] reach out to have syntax highlighting plugin updated
